### ISSUE TITLE
Is it possible to pull gps coordinates via MAVLink?

### ISSUE THREAD

**Issue by lida2003** [opendroneid/transmitter-linux#16]
I think the transmitter-linux get coordinates from [gpsd @ 938fb98](https://github.com/opendroneid/transmitter-linux/blob/main/gpsd), but I can't open the link. 

So is it possible to pull gps coordinates via MAVLink?

**Comment by friissoren** [comment]
I am not entirely sure of the detailed inner workings of the gpsd project.

The gpsd project is a git submodule in this project. I don't know why the link doesn't work directly. I have seen similar submodule links work earlier on Github. There must be some problem currently or maybe it is because gpsd is not hosted on Github?

Anyway, you can look in the [.gitmodules](https://github.com/opendroneid/transmitter-linux/blob/main/.gitmodules) file to find the full link to [gpsd](https://gitlab.com/gpsd/gpsd).

**Comment by lida2003** [comment]
> Anyway, you can look in the [.gitmodules](https://github.com/opendroneid/transmitter-linux/blob/main/.gitmodules) file to find the full link to [gpsd](https://gitlab.com/gpsd/gpsd).

Yes, I have got the code. It seems get gps coordinate through usb-serial. 

> So is it possible to pull gps coordinates via MAVLink?

I think it would be much convenient for ardupilot/px4 to use this if pull the gps coordinates from MAVLink, as there is a GPS on flight controller.

**Comment by friissoren** [comment]
> I think it would be much convenient for ardupilot/px4 to use this if pull the gps coordinates from MAVLink, as there is a GPS on flight controller.

I am quite sure that Ardupilot and PX4 already have full integrated support for creating remote ID signals, using whatever HW is available in the system. I haven't followed the progress in quite a while. There is some rather outdated information here:
https://github.com/opendroneid/opendroneid-core-c?tab=readme-ov-file#flight-controllers

Also, MAVLink does have dedicated messages for remote ID:
https://mavlink.io/en/messages/common.html#OPEN_DRONE_ID_BASIC_ID
